// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GameTable: typeof import('./src/components/GameTable/GameTable.vue')['default']
    GameTableBody: typeof import('./src/components/GameTable/GameTableBody.vue')['default']
    GameTableBodyCell: typeof import('./src/components/GameTable/GameTableBodyCell.vue')['default']
    GameTableBodyRow: typeof import('./src/components/GameTable/GameTableBodyRow.vue')['default']
    GameTableCell: typeof import('./src/components/GameTable/GameTableCell.vue')['default']
    GameTableHead: typeof import('./src/components/GameTable/GameTableHead.vue')['default']
    GameTableRow: typeof import('./src/components/GameTable/GameTableRow.vue')['default']
    GameTableTeamCell: typeof import('./src/components/GameTable/GameTableTeamCell.vue')['default']
    HowToModal: typeof import('./src/components/modals/HowToModal.vue')['default']
    PlayerInput: typeof import('./src/components/PlayerInput.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    ResultsModal: typeof import('./src/components/modals/ResultsModal.vue')['default']
    StatsModal: typeof import('./src/components/modals/StatsModal.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInformation: typeof import('./src/components/TheInformation.vue')['default']
  }
}

export { }
